name: cyber_friend_circle
description: "This app needs no description."
publish_to: 'none' 

version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_emoji: ^3.1.0
  cupertino_icons: ^1.0.8
  extended_image: ^8.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^10.7.5
  flutter_riverpod: ^2.5.1
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  langchain_lib:
    git:
      url: https://github.com/guchengxi1994/langchain_lib
  logging: ^1.2.0
  markdown_quill: ^4.1.0
  markdown_widget: ^2.3.2+6
  path_provider: ^2.1.4
  riverpod: ^2.5.1
  

dev_dependencies:
  build_runner: any  # dart run build_runner build
  flutter_launcher_icons: ^0.14.1 # dart run flutter_launcher_icons:generate
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter 
  isar_generator: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets: 
    - assets/avatars/
    - assets/bgs/
    - assets/emojis/
    - assets/AssetManifest.json


